# from go-ethereum:
name: linux build and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-amd64:
    name: Build and test linux/amd64
    runs-on: ubuntu-latest
    services:
      artemis:
        image: apache/activemq-artemis:latest-alpine
        ports:
          - 5672:5672
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.26.0
    - name: Check out code
      uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Get dependencies
      run: go mod download
    - name: Build
      run: go build -v -tags artemis -ldflags="-X 'github.com/makibytes/xmc/cmd.version=${{ github.ref_name }}'" -o amc .
    - name: Run unit tests
      run: go test -short ./...
    - name: Setup bats and bats libs
      uses: bats-core/bats-action@3.0.1
    - name: Run integration tests
      run: ./run-tests.sh
